[project]
name = "cw2"
version = "0.1.0"
description = ""
authors = [
    {name = "Denis",email = "bekishev.denis@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest (>=8.3.5,<9.0.0)",
    "isort (>=6.0.1,<7.0.0)",
    "flake8 (>=7.2.0,<8.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "coverage (>=7.8.0,<8.0.0)",
    "black (>=25.1.0,<26.0.0)",
    "pytest-cov (>=6.2.1,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
